// export const ipfsUpload = 'http://192.168.1.240:3000/upload';
// export const ipfsRetrieve = 'http://192.168.1.240:8080/ipfs/';
// export const mongoSmartContract = 'http://192.168.1.240:3000/mongo/smartcontract';
// export const mongoBrand = 'http://192.168.1.240:3000/mongo/models?brand=';
// export const mongoList = 'http://192.168.1.240:3000/mongo/lists?type=';
// export const mongoLanguage = 'http://192.168.1.240:3000/mongo/translations?language=';
// export const indexer = 'http://192.168.1.240:3000/indexer/';
export const ipfsUpload = 'https://securevehiclelogbook.com/api/upload';
export const ipfsRetrieve = 'https://securevehiclelogbook.com/ipfs/ipfs/';
export const mongoSmartContract = 'https://securevehiclelogbook.com/api/mongo/smartcontract';
export const mongoBrand = 'https://securevehiclelogbook.com/api/mongo/models?brand=';
export const mongoList = 'https://securevehiclelogbook.com/api/mongo/lists?type=';
export const mongoLanguage = 'https://securevehiclelogbook.com/api/mongo/translations?language=';
export const indexer = 'https://securevehiclelogbook.com/api/indexer/';